// <auto-generated />
using System;
using InventoryTracking.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryTracking.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InventoryTracking.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name");

                    b.Property<int>("Quantity");

                    b.HasKey("Id");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 9, 20, 20, 7, 2, 90, DateTimeKind.Local).AddTicks(9874),
                            Name = "Apples",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 9, 20, 20, 7, 2, 92, DateTimeKind.Local).AddTicks(5731),
                            Name = "Oranges",
                            Quantity = 7
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 9, 20, 20, 7, 2, 92, DateTimeKind.Local).AddTicks(5742),
                            Name = "Pomegranates",
                            Quantity = 55
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
